### ISSUE TITLE
Hi there o/

### ISSUE THREAD

**Issue by roidelapluie** [datadrivers/terraform-provider-nexus#1]
I see that this repo is quite recent.

Are you willing to accept third party contributions?

Thank you!

**Comment by Nosmoht** [comment]
Hi @roidelapluie,

sure, we just didn't had the time to add contribution and licence information. Feel free to send MR. We just started the repository thats why still some things are missing.

**Comment by roidelapluie** [comment]
Thanks, it would help if you could clarify the license thing :)

**Comment by Nosmoht** [comment]
I just added the GNU General Public License v3.

**Comment by Nosmoht** [comment]
I just changed the licence from GNU GENERAL PUBLIC LICENSE Version 3 to Mozilla Public License Version 2.0
