### ISSUE TITLE
Add support to enable and disable anonymous user access

### ISSUE THREAD

**Issue by ziurjam** [datadrivers/terraform-provider-nexus#100]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**

**Describe alternatives you've considered**
Disable and anonymous user in nexus 

**Additional context**

**Comment by anmoel** [comment]
Hello @ziurjam,

thanks for your report.
We will add this requested feature to our list and will implement them in the next few weeks.

regards 
André

**Comment by anmoel** [comment]
hi @ziurjam,

sry for the huge delay. 
This feature is implemented in version 1.14.0.

i will close this issue.

regards 
André
