### ISSUE TITLE
Errors when changing or deleting resources: Put: EOF

### ISSUE THREAD

**Issue by Jfmask** [datadrivers/terraform-provider-nexus#101]
Hello.

Thank you for the great Nexus management tool, which helps a lot with our work.

However, we have encountered problems when updating or deleting resources.

**Describe the bug**

When resources are changed and Terraform is restarted, errors like the following occurs:

```
nexus_role.write_only_all: Modifying... [id=nx-write-only-all]

Error: Put "https://nexus-host/service/rest/beta/security/roles/nx-write-only-all": EOF
```

Running the same command again successfully removes or modifies resources.

The problem occurs not only with Nexus roles, but also with users. It is difficult to reproduce the problem because the error does not occur every time.

It is suspected that the problem is with Nexus, Nexus Proxy or Nginx behind which Nexus is running, but we have not been able to find out at which stage the error occurs.

**Expected behavior**

The changes go through the first time.

**Log output**

The nexus provider related log messages can be found here: https://pastebin.com/raw/QSq0pPcA

**Comment by anmoel** [comment]
Hi @Jfmask,

can you please describe your environment so we can try to reproduce this bug?

Or set the environment variable `TF_LOG` to `DEBUG` and attach the output to this ticket.

regards
André

**Comment by Jfmask** [comment]
@anmoel, thank you for the quick response. I have added a link to the debug log.

**Comment by Jfmask** [comment]
I have updated the first post with non-expiring link to log with error messages: https://pastebin.com/raw/QSq0pPcA

**Comment by Jfmask** [comment]
I think, the reason is the following: https://github.com/travelaudience/nexus-proxy/issues/26
We use that Helm Chart to provision Nexus with Nexus Proxy, thus proxy can drop requests from the terraform-provider-nexus.
