### ISSUE TITLE
full destroy fail to remove repo

### ISSUE THREAD

**Issue by SebTardif** [datadrivers/terraform-provider-nexus#108]
nexus_repository.quay_iso: Destroying... [id=quay.io]
nexus_repository.iron-bank-docker: Destroying... [id=iron-bank-docker]
╷
│ Error: could not delete repository 'iron-bank-docker': HTTP: 500, ERROR: (ID 1331a125-7e63-4ea3-bd33-7725d5967439) org.sonatype.goodies.common.MultipleFailures$MultipleFailuresException: Failed to delete facets; 1 failure
│
│
╵
╷
│ Error: could not delete repository 'quay.io': HTTP: 500, ERROR: (ID dcc5c976-506a-4344-9d1c-84e5aa16dbb2) org.sonatype.goodies.common.MultipleFailures$MultipleFailuresException: Failed to delete facets; 1 failure
│
│
╵

**Comment by anmoel** [comment]
HI @SebTardif,

thanks for your contribution. 

Is the nexus repository manager 3 also managed by terraform and was first destroyed? 
Do you have some example, how to reproduce this error.
 
thanks in advance and regards
André

**Comment by SebTardif** [comment]
We noticed tat the error doesn't happen if the storage is using default. So the problem occur when the storage have been set to a different value.

**Comment by dcl4k** [comment]
@anmoel 
I see this was marked as Closed, is there reason to think this has been resolved? I am still running into this with Nexus 3.75.0-06 and provider version 2.5.0

I realize the provider hasn't been tested on this version of Nexus, so perhaps that's the issue? 

could not delete repository 'docker-group': HTTP: 500, ERROR: (ID 34fd257f-a54b-4306-b7c3-b74778932ace) org.sonatype.nexus.common.stateguard.InvalidStateException: Invalid state: STOPPED; allowed: [STARTED]

Additionally, this is happening with repositories that are using the "default" blob.

**Comment by jonasdemoor** [comment]
Hi, I'm also seeing this on Nexus Pro 3.85.0-03 with an S3 blob store. This happens both on a full destroy and deleting e.g. a Docker group repository and a Docker member repository of the group at the same time. Notably when the group repository is deleted first.

Deleting either of them separately first, in any order, works in my case as a workaround.
