### ISSUE TITLE
Missing option for Docker Proxy: Foreign Layer Caching

### ISSUE THREAD

**Issue by SebTardif** [datadrivers/terraform-provider-nexus#109]
https://help.sonatype.com/repomanager3/formats/docker-registry/foreign-layers

**Comment by anmoel** [comment]
hi @SebTardif,

please excuse my late reply.
Unfortunately this attribute can not be configured via the REST API yet.
I will create a feature request at sonatype.

**Comment by anmoel** [comment]
this issue ist not blocked anymore


![Image](https://github.com/user-attachments/assets/3847203a-5b53-4809-bbf6-dc6079d97da9)

**Comment by anmoel** [comment]
This Issue is implemented in version v2.5.0
