### ISSUE TITLE
Ability to import existing resources

### ISSUE THREAD

**Issue by fad3t** [datadrivers/terraform-provider-nexus#118]
Hello,

Are there any plans to add support for the import of resources in the future?
I didn't see any reference to it in the documentation, and the `terraform import` command for `nexus_` resources returns an error, so I believe this part isn't implemented yet.
This provider is great (thx for this) and it would be nice to be able to manage existing resources as well.

Fred.

**Comment by anmoel** [comment]
Hi Fred,

Thanks for your message. I will add this behaviour to our implementation list. At this moment we working on a refactoring of the repository resource. This work will released as new major version and after this big change, we can start the implementation of import features. 

Regards 
André

**Comment by anmoel** [comment]
we add the documentation of the import commands in the next release. v1.16.0

**Comment by anmoel** [comment]
it is implemented. use [v1.16.1](https://github.com/datadrivers/terraform-provider-nexus/releases/tag/v1.16.1) or greater
