### ISSUE TITLE
Option to set NuGet Proxy Protocol Version

### ISSUE THREAD

**Issue by do360now** [datadrivers/terraform-provider-nexus#134]
We are trying to use the option of V2 for the NuGet Proxy Protocol Version, but in terraform resource "nexus_repository" "nuget_proxy" this option is not available.  Or, is it?
Please let me know if you need more information.
Thanks!

**Comment by anmoel** [comment]
Hi @do360now,

thanks for your report.
This feature is implemented in version v1.15.0.
Please test this feature and reopen this issue if it don't work.

regards 
André

**Comment by ClissonFlorian** [comment]
Hi @anmoel ,

It does not work. Actually when you set the value nuget_version to "V2", the terraform provider apply "V3".

Note : The provider detect properly that the nuget_version is not the one expected.

nuget_proxy {
    query_cache_item_max_age = "3600"
    nuget_version = "V2"
  }
