### ISSUE TITLE
nexus_repository - support bearerToken authentication type

### ISSUE THREAD

**Issue by mpailloncy** [datadrivers/terraform-provider-nexus#135]
**Is your feature request related to a problem? Please describe.**

It's currently not possible to set type="bearerToken" of the http_client/authentication block for nexus_repository:

```
resource "nexus_repository" "npmjs_proxy" {
...
  http_client {
    authentication {
      type     = "bearerToken"
      password = "TOKEN_VALUE"
    }
  }
...
}

```

When trying to apply, it fails with:

> Error: expected http_client.0.authentication.0.type to be one of [ntlm username], got bearerToken

datadrivers/nexus version: 1.14.0

**Describe the solution you'd like**

As it's an option available in Nexus3, would be great to have it available via datadrivers/nexus too.

**Describe alternatives you've considered**

The current workaround I'm using is to set the field through the UI, and then ignore any change on the type field with:

```
  lifecycle {
    ignore_changes = [
        http_client.0.authentication.0.type
    ]
  }
```

**Additional context**

**Comment by anmoel** [comment]
Hi @mpailloncy,

the feature request is implemented in version v1.15.0. 
Please check this feature and reopen this issue or create a new if it doesn't work.

regards 
André
