### ISSUE TITLE
Import user functionality

### ISSUE THREAD

**Issue by phlegx** [datadrivers/terraform-provider-nexus#136]
Would be nice to have an import functionality for the `nexus_security_user`

**Comment by EugenMayer** [comment]
What does import mean here? You can import a state via terraform already, anything else would be unusual to be done by the provider. Since there is a data resource for users already, i'am not sure what an 'import' would be here - could you explain?

**Comment by anmoel** [comment]
we add the documentation of the import commands in the next release. v1.16.0

**Comment by anmoel** [comment]
it is implemented. use [v1.16.1](https://github.com/datadrivers/terraform-provider-nexus/releases/tag/v1.16.1) or greater
