### ISSUE TITLE
Roles always showing as having changes

### ISSUE THREAD

**Issue by abby-gourlay** [datadrivers/terraform-provider-nexus#137]
**Describe the bug**
I've created roles on Nexus but on each plan terraform thinks there's changes to be made. From reading #63 it seems like a regression as that's exactly the same behavior I'm getting where the description and name are the ID, and all the privilege's are set to be added

```
  # nexus_role.docker_upload will be updated in-place
  ~ resource "nexus_role" "docker_upload" {
      ~ description = "nexus-docker-upload" -> "Allows users to upload images to the docker repository"
        id          = "nexus-docker-upload"
      ~ name        = "nexus-docker-upload" -> "Docker Upload"
      ~ privileges  = [
          + "nx-repository-view-docker-docker-hosted-add",
          + "nx-repository-view-docker-docker-hosted-edit",
          + "nx-repository-view-docker-docker-hosted-read",
        ]
        # (2 unchanged attributes hidden)
    }
```
Currently using 
Nexus Pro 3.32.0-03 
Terraform v1.0.6
on linux_amd64
+ provider registry.terraform.io/datadrivers/nexus v1.14.0

**Comment by anmoel** [comment]
Hi @abby-gourlay,

thanks for your report.
Unfortunately i can't reproduce this problem with following code:
```hcl
resource "nexus_repository" "docker_hosted" {
  name   = "docker-hosted"
  format = "docker"
  type   = "hosted"

  storage {
    blob_store_name                = "default"
    strict_content_type_validation = true
    write_policy                   = "ALLOW_ONCE"
  }

  docker {
    force_basic_auth = false
    http_port        = 5000
    https_port       = 0
    v1enabled        = false
  }
}

resource "nexus_role" "docker_upload" {
  roleid      = "nexus-docker-upload"
  name        = "Docker Upload"
  description = "Allows users to upload images to the docker repository"
  privileges  = [
    "nx-repository-view-docker-docker-hosted-add",
    "nx-repository-view-docker-docker-hosted-edit",
    "nx-repository-view-docker-docker-hosted-read",
  ]

  depends_on = [
    nexus_repository.docker_hosted
  ]
}
```

**Comment by TrueTechy** [comment]
Hi there, 

Apologies for the major delay in response. 

I was finishing up importing our instances into terraform this week and noticed that in the API responses for only some of our roles we have multiple enteries, one which says the source is default, and the other LDAP (which we do use for authentication)

```
  {
    "id": "nexus-docker-upload",
    "source": "LDAP",
    "name": "nexus-docker-upload",
    "description": "nexus-docker-upload",
    "privileges": [],
    "roles": []
  },
  {
    "id": "nexus-docker-upload",
    "source": "default",
    "name": "Docker Upload",
    "description": "Allows users to upload images to the docker repository",
    "privileges": [
      "nx-repository-view-docker-devops-docker-hosted-edit",
      "nx-repository-view-docker-devops-docker-hosted-read",
      "nx-repository-view-docker-devops-docker-hosted-add"
    ],
    "roles": []
  },
  ```
This is one of the roles that keeps showing as having changes required. I looked at some of our other roles which also have this second LDAP entry, but in all those which are fine the LDAP entry shows up after the default entry. I was wondering if this is maybe confusing the provider and it's just picking the first it finds, which if it's the LDAP one then it shows as being empty and thus all the changes.

Looking at the API docs it says there's an option to filter by source (`/service/rest/v1/security/roles?source=default`), filtering on "default" then gave me the list without the LDAP enteries which I'd imagine would work better in the provider, though I can't test that to say with certainty

**Comment by TrueTechy** [comment]
@anmoel I managed to get the change I was suggesting tested. 

We're currently using an older version of the provider so I tested it with that, but I changed the following line https://github.com/datadrivers/go-nexus-client/blob/b394aac8fb8dd96f6b95bdb48947c81cf0ef8e86/role.go#L52 to

`body, resp, err := c.Get(rolesAPIEndpoint + "?source=default", nil)`

and that has allowed the provider to see that there are no changes required after removing the lifecycle blocks. 

I'm not sure how this would be best implemented but I hope this helps
