### ISSUE TITLE
Add a timeout option when creating the client for nexus

### ISSUE THREAD

**Issue by marcelobartsch** [datadrivers/terraform-provider-nexus#138]
**Is your feature request related to a problem? Please describe.**
In our setup, we are connected to an LDAP server which have a huge number of users/groups and also is located geographically distant from the nexus server , so when creating roles mapped to LDAP groups it works, but when refreshing , it fails with a timeout 

Error: Get "https://xxxxxxxxxxxxx/service/rest/v1/security/roles": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

as it takes more than 30 seconds to return the list [1], it would be nice to be able to configure a higher timeout setting on the provider for those cases

[1] https://github.com/datadrivers/go-nexus-client/blob/master/client.go#L96

**Describe the solution you'd like**
as state above, be able to configure a custom timeout value for the provider connection

**Describe alternatives you've considered**
remove the roles from TF as a workaround

**Additional context**
nexus plus LDAP

**Comment by jdelee** [comment]
[related to #139](https://github.com/datadrivers/terraform-provider-nexus/issues/139)
