### ISSUE TITLE
nexus_repository member_names list order not adhered to

### ISSUE THREAD

**Issue by MG2R** [datadrivers/terraform-provider-nexus#140]
**Describe the bug**
The order of member_names in my repository group is not adhered to. Repositories are seemingly randomly (though deterministically) ordered upon creation, after which the order is never enforced again. 

**To Reproduce**
Using provider version 1.14.0, Terraform 0.14.

Define a repository group:
```
resource "nexus_repository" "group" {                                             
  name   = "public"                                                              
  format = "maven2"                                                              
  type   = "group"

  [...]

  group {                                                                        
    member_names = [                                                             
      "bcs-repo-releases",                                                       
      "bcs-repo-snapshots-legacy",                                               
      "central",                                                                 
      "apache-snapshots",                                                        
    ]                                                                            
  }                                                                              
}    
```

The plan for this lists the `member_names` as
```
      + group {
          + member_names = [
              + "apache-snapshots",
              + "bcs-repo-releases",
              + "bcs-repo-snapshots-legacy",
              + "central",
            ]
        }
```
This order seems sorted alphabettically.

Applying this plan ends up creating a repository group with the following member list:
- bcs-repo-snapshots-legacy
- apache-snapshots
- bcs-repo-releases
- central

Behavior of note:
* Order is seemingly random. Adding or removing different members results in a wildly different list.
* Re-ordering that list in Nexus does not trigger Terraform to rever the order. Order is not changed after initial creation.
* Removing the group repo in Nexus and re-creating with Terraform results in the same order as listed above. Order seems to be deterministic. 

**Expected behavior**
1. The resulting group repo in nexus should have the member list order from the original code
2. The plan should reflect the order in the code.
3. The order should be restored to the one in code if it's manually changed in Nexus

I've found bug #25 but it doesn't seem related as the order is not sorted, rather seemingly random.

**Comment by anmoel** [comment]
please use the new nexus_repositoy_maven_group resource. this resource is deprecated

**Comment by anmoel** [comment]
this issue is closed, because the resource is deleted in the new release. 
if the error still exists in the new resources, please open a new ticket.
