### ISSUE TITLE
PROPOSAL: Split repository entity by repo types.

### ISSUE THREAD

**Issue by akaRem** [datadrivers/terraform-provider-nexus#15]
Currently all the possible repositories are backed by the same resource called "nexus_repository".

The problem with this approach is that..

1. It's hard to use, for example, currently in VSCode intellisense checks and advises apt-related configuration sections for docker repos (it doesn't check conflicts)

<img width="620" alt="image" src="https://user-images.githubusercontent.com/1472728/79462018-40db8780-7ff7-11ea-87f2-f83fb38c884c.png">

2. It's hard to extend.
For example, here you can see the number of fields which should be modified to add just one additional repo https://github.com/datadrivers/terraform-provider-nexus/pull/8/files 
If all the possible repositories will be supported by provider (see the list below), then the resource "nexus_repository" will become unmaintainable and unreadable.

<img width="214" alt="image" src="https://user-images.githubusercontent.com/1472728/79459559-bf362a80-7ff3-11ea-9112-50a471232b92.png">

**Proposal**

Split repository by type and format (they have quite different configurations anyways).

Usage example in Terraform:

```hcl
resource "nexus_repository_apt_hosted" "my_apt_hosted_repo" {
  name   = "my-apt"    
  distribution = "bionic"

  signing {
    keypair    = "<keypair>"
    passphrase = "<passphrase>"
  }

  storage {
    blob_store_name                = "default"
    strict_content_type_validation = true
    write_policy                   = "ALLOW_ONCE"
  }
}
```

From code point of view, it will produce quite similar files forked files from existing terraform-provider-nexus/nexus/resource_repository.go

Pros:
+ better intellisense support
+ better isolation: impl. of additional repository type will not affect any existing implementations
+ much easier to read source code
+ less test cases to test

Cons:
- Code duplication for some fields like "storage" field which is applicable for multiple repo types.
- Possible breaking change (*)
- Some work to do

(*) Breaking change can be postponed by:
- Building alternative resources besides existing multiresources.
- Releasing current version under a tag
- Dropping current implementation later with major release

**Comment by akaRem** [comment]
Me and @kuzmacska can take actions to implement these changes and send PRs later if you guys agree with this proposal.

**Comment by Nosmoht** [comment]
Sounds good. Feel free to send a PRs as my time is currently very limited to continue working on the project.

**Comment by anmoel** [comment]
we create a project for this issue and creates a task for each repository resource / data source. The importants repos are created. i will close this issue. 

link to project: https://github.com/datadrivers/terraform-provider-nexus/projects/2
