### ISSUE TITLE
impossible to set V2 as value for the nuget_version paremeter

### ISSUE THREAD

**Issue by ClissonFlorian** [datadrivers/terraform-provider-nexus#165]
Hi @anmoel ,

It does not work. Actually when you set the value nuget_version to "V2", the terraform provider apply "V3".

Note : The provider detect properly that the nuget_version is not the one expected.

nuget_proxy {
    query_cache_item_max_age = "3600"
    nuget_version = "V2"
  }

_Originally posted by @ClissonFlorian in https://github.com/datadrivers/terraform-provider-nexus/issues/134#issuecomment-1002465885_

**Comment by anmoel** [comment]
Hi @ClissonFlorian,

thanks for your Report. Unfortunately there is a bug in the nexus REST API. 
We must wait for a new nexus version which includes the fix of this issue: https://issues.sonatype.org/browse/NEXUS-28791

kind regards
André

**Comment by anmoel** [comment]
Hi @ClissonFlorian,

the sonatype dev team fixed the bug in the last versions. I add a test for the nuget version and it is working now

regards
André
