### ISSUE TITLE
Mistake in provider documentation

### ISSUE THREAD

**Issue by ranebull** [datadrivers/terraform-provider-nexus#196]
Hello!
I see mistake in document https://registry.terraform.io/providers/datadrivers/nexus/latest/docs/resources/security_realms.
Import example need `terraform import nexus_security_realms.example active` not `ldap_realms`.

Thank you!

**Comment by anmoel** [comment]
Hi @ranebull, 

thank you for the usage of our provider and your request. The documentation for the import command will be fixed in the next release.

regards
André
