### ISSUE TITLE
Group members in repository resource are not updated

### ISSUE THREAD

**Issue by matglas** [datadrivers/terraform-provider-nexus#20]
**Summary**
When a nexus_repository of the type group has group->member_names set it does not add new members when they are added to the list after first apply.

**Reproduce**

1. Create a resource group.

```
# ... repository definition for docker_hosted. 

resource "nexus_repository" "docker_group" {
  depends_on = [nexus_repository.docker_hosted]
  name   = "docker-group"
	format = "docker"
	type   = "group"
	online = true

	group {
		member_names = ["docker-hosted"]
	}

	# ... rest or resource configuration.
}
```

2. Apply changes

3. Add 2rd repository.

```
# ... repository definition for docker_hosted and docker_proxy. 

resource "nexus_repository" "docker_group" {
  depends_on = [nexus_repository.docker_hosted,nexus_repository.docker_proxy]
  name   = "docker-group"
	format = "docker"
	type   = "group"
	online = true

	group {
		member_names = ["docker-hosted","docker-proxy"]
	}

	# ... rest or resource configuration.
}
```
4. Apply changes.

**Expected result**

A 2nd repository created and added as a member to the docker group members.
 
**Current result**

A 2nd repository is created but not added to the docker group members.

**Comment by Nosmoht** [comment]
Hi @matglas,

could you please test with v1.4.0 just to confirm the bug still exists or not?

**Comment by matglas** [comment]
The bug is still there. It sees it need to change it and says it has changed it but it did not change.

**Comment by Nosmoht** [comment]
I'll check that

**Comment by Nosmoht** [comment]
Hi @matglas ,

this should be fixed with https://github.com/datadrivers/terraform-provider-nexus/releases/tag/v1.4.1.

**Comment by Nosmoht** [comment]
@matglas could you please test with provider version v1.5.3 and let us know your results?
