### ISSUE TITLE
Some objects are not get updated.

### ISSUE THREAD

**Issue by fog1985** [datadrivers/terraform-provider-nexus#22]
Hi guys,

I tried to use resources as follow:
```
resource "nexus_repository" "docker_hosted" {
  name   = "docker-hosted-test"
  format = "docker"
  type   = "hosted"
  online = true

  docker {
    http_port        = 8083
    https_port       = 8084
    force_basic_auth = true
    v1enabled        = true
  }

  storage {
    blob_store_name                = "default"
    strict_content_type_validation = true
    write_policy                   = "ALLOW_ONCE"
  }
}
```
In this resource, port update or repo name update for example doesn't update it on Nexus server. Even though TF reports as there is a change for in-place update.

And one more:
```
resource "nexus_blobstore" "tf-test" {
  name = "blobstore-0101"
  type = "File"
  path = "/nexus-data/blobstore-01"

  soft_quota {
    limit = 1024
    type  = "spaceRemainingQuota"
  }
}
```
In this resource, `soft quota` is set up to 0 by default which is incorrect set-up at all. Despite it being provided as 1024 in code. After changes and re-applying still no effect. Even though TF reports as there is a change for in-place updates. It goes through. Says updated and no effect on the Nexus server.

**Comment by Nosmoht** [comment]
Hi @fog1985 ,

this should be fixed with https://github.com/datadrivers/terraform-provider-nexus/releases/tag/v1.4.1.

**Comment by Nosmoht** [comment]
Hi @fog1985 ,

could you please test with current release?

**Comment by fog1985** [comment]
Hi @Nosmoht ,
Thank you a lot for the prompt response to this bug!
It has been fixed and works as expected now.
