### ISSUE TITLE
NPM Repository

### ISSUE THREAD

**Issue by siobhanaka** [datadrivers/terraform-provider-nexus#23]
Hi,  I see there are a bunch of repo formats (bower, nuget, docker etc.) - but no npm... are there plans to include npm repositories?
Thanks S

**Comment by Nosmoht** [comment]
Hi @siobhanaka ,

NPM is now implemented.

**Comment by Nosmoht** [comment]
Hi @siobhanaka ,

NPM support was added with https://github.com/datadrivers/terraform-provider-nexus/commit/e117f28b9d6cfcab069591f0af066d076638c8ac.

Could you please test with release v1.4.0?

**Comment by siobhanaka** [comment]
Works a treat @Nosmoht , thanks
