### ISSUE TITLE
Order of repositories in docker repository group is not respected

### ISSUE THREAD

**Issue by matglas** [datadrivers/terraform-provider-nexus#25]
**Summary**
When I define a docker repository group the order of the items in the `member_names` is not respected which leads to unreliable results when image are pulled.

**Reproduce**
- Create two repos. One for a hosted variant and one for a proxy. As they are ordered by name please name the hosted repo `z-repo` and the proxy repo `a-repo`.

- Define a repository group with the hosted as first item.

```
# ... repository definition for docker_hosted and docker_proxy. 

resource "nexus_repository" "docker_group" {
  depends_on = [nexus_repository.z_repo,nexus_repository.a_repo]
  name   = "docker-group"
	format = "docker"
	type   = "group"
	online = true

	group {
		member_names = ["z-repo","a-repo"]
	}

	# ... rest or resource configuration.
}
```

- Create an image and push this to the proxied repo with the image tag `test:a`
- Create an image and push this to the hosted repo on nexus with the same image tag.
- Pull the image with the tag from the `docker-group` repo.

**Expected result**
The image from the `z-repo` would be pulled.

**Actual result**
The image from the `a-repo` is pulled.

**Comment by matglas** [comment]
Checked still a problem in v1.4.0.

**Comment by Nosmoht** [comment]
Hi @matglas,

this should be fixed with https://github.com/datadrivers/terraform-provider-nexus/releases/tag/v1.4.1.
