### ISSUE TITLE
npm proxy repository remote url does not change

### ISSUE THREAD

**Issue by c4rlier** [datadrivers/terraform-provider-nexus#26]
Hi,
when changing the remote_url parameter on an existing remote repository of npm format the change is accepted as `will be updated in place` by the provider and executed, however the underlying nexus parameter does not change.

Please let me know if you would like further details.

**Comment by Nosmoht** [comment]
Hi @c4rlier ,

this should be fixed with https://github.com/datadrivers/terraform-provider-nexus/releases/tag/v1.4.1.

**Comment by Nosmoht** [comment]
Hi @c4rlier,

could you please test with current release?
