### ISSUE TITLE
nuget proxy repositories parameter missing

### ISSUE THREAD

**Issue by c4rlier** [datadrivers/terraform-provider-nexus#27]
Nexus API returns the following error when I try to create a nuget proxy repository. I could not find any parameters unique to nuget proxy repositories in the code. However Nexus doesn't seem to allow creating a nuget proxy repository with this parameter missing.
```
Error: could not create repository 'nuget-proxy': HTTP: 400, [ {
  "id" : "PARAMETER nugetProxy",
  "message" : "must not be null"
} ]
```

Furthermore I submitted the following issue to sonatype (not sure if under the right repo!)  as the api endpoints description ( and possibly implementation ) has an error.
https://github.com/sonatype-nexus-community/nexus-scripting-examples/issues/7

**Comment by Nosmoht** [comment]
Hi @c4rlier,

this feature is not implemented yet. I'll add it soon.

**Comment by Nosmoht** [comment]
Fixed with https://github.com/datadrivers/terraform-provider-nexus/pull/36. Will be releases in v1.5.0.

**Comment by c4rlier** [comment]
Already tested, thanks for the fix! Will close this issue if you don't mind.
