### ISSUE TITLE
Support for security_ssl_certiticate resource

### ISSUE THREAD

**Issue by pickgr** [datadrivers/terraform-provider-nexus#313]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There is a configuration available at

https://_nexus server_/#admin/security/sslcertificates

where one can add/manage SSL certificates.

https://help.sonatype.com/repomanager3/nexus-repository-administration/configuring-ssl

### New or Affected Resource(s)/Data Source(s)

nexus_security_ssl_certificate

### Pro feature

- [ ] Yes. Pro license Required

### Potential Terraform Configuration

```HCL
resource "tls_private_key" "this" {
  algorithm = "RSA"
}

resource "nexus_security_ssl_certificate" "this" {
  pem = tls_private_key.this.private_key_pem
}

or the PEM could be loaded from local disk or AWS Secrets Manager, etc.

Note that it should probably be marked as 'sensitive' in terraform so it's not exposed in plan output, etc.

Unfortunately, it appears that nexus doesn't currently support an API for managing these certs:

https://help.sonatype.com/repomanager3/integrations/rest-and-integration-api/security-management-api
```

### References

- https://help.sonatype.com/repomanager3/nexus-repository-administration/configuring-ssl
- https://help.sonatype.com/repomanager3/integrations/rest-and-integration-api/security-management-api

**Comment by chris-ruecker** [comment]
This configuration interface is for adding certificates to the Truststore, which is possible via this resource:
https://registry.terraform.io/providers/datadrivers/nexus/latest/docs/resources/security_ssl_truststore
