### ISSUE TITLE
Support for Docker Subdomain Connector

### ISSUE THREAD

**Issue by nhat-tong** [datadrivers/terraform-provider-nexus#368]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Since Nexus 3.40.0, Sonatype add a new functionality **Subdomain Connector** as a way to manage routing to docker repository instead of using a port connector. This is also exposed on the API:
```JSON
{
  "name": "docker-repo",
  "url": "URL",
  "online": true,
  "storage": {
    "blobStoreName": "docker-repo",
    "strictContentTypeValidation": true
  },
  "group": {
    "memberNames": [
      "dockerhub-proxy"
    ]
  },
  "docker": {
    "v1Enabled": false,
    "forceBasicAuth": true,
    "httpPort": null,
    "httpsPort": null,
    "subdomain": null <-- this one
  },
  "format": "docker",
  "type": "group"
}
```
Please add support for this new functionality.
### New or Affected Resource(s)/Data Source(s)

nexus_repository_docker_group

### Pro feature

- [X] Yes. Pro license Required

### Community Plugin

No

### Potential Terraform Configuration

```HCL
resource "nexus_repository_docker_group" "docker_group" {
  name   = "docker-group"
  online = true

  docker {
    force_basic_auth = true
    v1_enabled = false
    subdomain = "docker-group" <-- new attribute here
  }
}
```

### References

https://help.sonatype.com/repomanager3/nexus-repository-administration/formats/docker-registry/docker-subdomain-connector

**Comment by ktibi** [comment]
No only for group but also for hosted or proxy.

**Comment by AYDEV-FR** [comment]
I also need this feature 👍

**Comment by btribit** [comment]
I have added two PRs for this. One for the go-nexus-client wiring to get it to provide the subdomain attribute, and then also here for the terraform provider bits. I tested this with a licensed nexus repo and the dev_providered it into terraform code and it works a treat. If there are any odds and ends to make these PRs reviewable, I'm all ears.

**Comment by anmoel** [comment]
pull request is merged and will be released with some other PR

**Comment by anmoel** [comment]
release with version https://github.com/datadrivers/terraform-provider-nexus/releases/tag/v2.1.0
