### ISSUE TITLE
Destroy action should delete blobstore after destroing repos

### ISSUE THREAD

**Issue by android-leha** [datadrivers/terraform-provider-nexus#42]
If I'm destroying all my repos and blobstore I got error:
`
Error: could not delete blobstore "default": HTTP: 500, ERROR: (ID cc540e55-32c3-49c8-895c-1821fb7ec437) java.lang.IllegalStateException: BlobStore default is in use and cannot be deleted
`

If I retry destroy command again, it is able to destroy

**Comment by Nosmoht** [comment]
As the error message says: you can't delete a blobstore in use. So with your first run, Terraform destroys the repos and parallel the blobstore, which is still in use.
With your second TF run, repos are already deleted and blobstores can be deleted.

Do you have a resource `nexus_blobstore.default` which you can use for Terraform dependency? Just wondering as `default` blobstore is by default in Nexus.

**Comment by android-leha** [comment]
Yes, I have.

But I think, provider should automatically recognize dependencies between repos and blobstores, and start to process blobstores, only after all repositories are deleted.

**Comment by Nosmoht** [comment]
This is a standard Terraform feature.

```hcl
resource  "nexus_blobstore" "demo"  {
  name = "demo"
...
}

resource "nexus_repository" "demo" {
  name = "demo"
  ...
  storage {
     blob_store_name = nexus_blobstore.demo.id
     ...
  }
```

**Comment by android-leha** [comment]
Thank you for help.
Readme confused me a little, so I thought it is not possible to define link to resource instead of name.

Just want to mention for group repositories need to define name

```
    group {
        member_names = [
            nexus_repository.maven_proxy_central.name,
            nexus_repository.maven_proxy_spring.name,
            nexus_repository.maven_hosted_releases.name,
        ]
    }
```
