### ISSUE TITLE
Proxy without authentication section

### ISSUE THREAD

**Issue by boubech** [datadrivers/terraform-provider-nexus#43]
Hi ! 
When I declare a proxy repository (maven2 and pypi) without authentification, I have the message : 

> HTTP: 400, [ {
  "id" : "PARAMETER type",
  "message" : "may not be empty"
} ]

    resource nexus_repository maven_sonatype_public {
    name   = "sonatype-public"
    type   = "proxy"
    format = "maven2"
    online = true

    proxy {
        remote_url  = "https://oss.sonatype.org/content/repositories/public/"
        content_max_age  = 1440
        metadata_max_age = 1440
    }
    negative_cache {
        enabled = true
        ttl     = 1440
    }
    storage {
        blob_store_name                = "default"
        strict_content_type_validation = true
    }
    maven {
        version_policy = "MIXED"
        layout_policy  = "STRICT"
    }

    http_client {
    }
  

Client : 1.6.0
Server:  3.23.0-03

**Comment by Nosmoht** [comment]
Hi @boubech ,

i believe following code is missing
```hcl
http_client {
	authentication {
		type = "username"
	}
}
```

**Comment by boubech** [comment]
@Nosmoht That's true, it works with this section , but I doesn't want to use http authentication for my proxy repository.

**Comment by Nosmoht** [comment]
I'll check API of Nexus and see what we can do ;). I've this small code snippet in all proxy repos evenso we are using HTTPS for everything.

**Comment by Nosmoht** [comment]
Hi @boubech ,

i've found the error. Will be fixed within next release, which we can hopefully release today.

**Comment by ruedigerblock** [comment]
Moin guys,
we created a new release v1.6.2 which should address this issue.
Please check ;-)

**Comment by Nosmoht** [comment]
Hi @boubech ,

can we close the issue or is there anything left to get it working for you?

**Comment by boubech** [comment]
> Hi @boubech ,
> 
> can we close the issue or is there anything left to get it working for you?

Sorry for the delay,
It's work..
