### ISSUE TITLE
Maven Group - 404

### ISSUE THREAD

**Issue by boubech** [datadrivers/terraform-provider-nexus#44]
Hi !
When I want to declare a Maven group repository, a 404 error occurred.
Example : 

    resource "nexus_repository" "maven_group_all" {
    name   = "maven-public-2"
    format = "maven2"
    type   = "group"
    group {
        member_names = [
            "maven-central",
            "maven-releases",
            "maven-snapshots"
        ]
    }
    }
   
Provider version : 1.6.0
Server version : 3.23.0-03

**Comment by android-leha** [comment]
Hi @boubech 

Also faced same issue.
The problem in Nexus itself. REST API is not avaliable.

This is sonatype ticket: https://issues.sonatype.org/browse/NEXUS-23080

Looks like they fixed it in next version 3.24.0

Waiting for next release=)

**Comment by boubech** [comment]
@android-leha Thank you

**Comment by Michenux** [comment]
The release 3.24.0 is here.
[https://help.sonatype.com/repomanager3/release-notes#ReleaseNotes-NexusRepositoryManager3.24.0](Nexus 3.24.0)

**Comment by Nosmoht** [comment]
Hi @Michenux, @android-leha and @boubech,

could you please test with provider [v1.8.0](https://github.com/datadrivers/terraform-provider-nexus/releases/tag/v1.8.0) and Nexus 3.24.0. We have added some tests for Maven proxy which work fine so far.
