### ISSUE TITLE
Data - Nexus Repository - Group

### ISSUE THREAD

**Issue by boubech** [datadrivers/terraform-provider-nexus#45]
Hi ! 

When I want to get repository from data, this error occured : `Error: Invalid address to set: []string{"group"}`

     data "nexus_repository" "maven_public" {
          name = "maven_public"
     }

**Comment by Nosmoht** [comment]
Hi @boubech ,

i'll check and fix this soon.

**Comment by Nosmoht** [comment]
I can verify that this error only occurs if the repository is of type `group`. It works well for repositories of type `hosted` and `proxy`.

**Comment by Nosmoht** [comment]
Hi @boubech ,

this should be fixed with [v1.6.2](https://github.com/datadrivers/terraform-provider-nexus/releases/tag/v1.6.2)

**Comment by boubech** [comment]
It works ! 
Thank you.
