### ISSUE TITLE
Support for Cleanup Policies

### ISSUE THREAD

**Issue by Michenux** [datadrivers/terraform-provider-nexus#473]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I would like to be able to manage the cleanup policies in Terraform.
The nexus API has been updated in 3.70 so you can now define cleanup policies with the API.
https://help.sonatype.com/en/cleanup-policies-api.html

### New or Affected Resource(s)/Data Source(s)

nexus_cleanup_policy

### Pro feature

- [ ] Yes. Pro license Required

### Potential Terraform Configuration

```HCL
resource "nexus_cleanup_policy" {
  name: "delete-not-downloaded-after-30d",
  notes: "Delete artifacts if not downloaded within 30 days",
  criteriaLastBlobUpdated: 0,
  criteriaLastDownloaded: 30,
  criteriaReleaseType: "RELEASES",
  criteriaAssetRegex: "",
  retain: null,    # this attribute only for pro version.
  format: "maven2"
}
```

**Comment by chris-ruecker** [comment]
Hi @Michenux , we are working on implementing this at the moment and it will be in the next release. 
There is a quite old issue for this already: 
https://github.com/datadrivers/terraform-provider-nexus/issues/226

**Comment by MrKich** [comment]
@chris-ruecker is it still planned for the next release?
