### ISSUE TITLE
Missing parameters are required for resource(repository) creation. Example declaration statement missing?.

### ISSUE THREAD

**Issue by 5obol** [datadrivers/terraform-provider-nexus#48]
Hi guys

Can you please point me at all possible parameters for the resources creation?
E.G. I am creating repository of type proxy and format apt :

```resource "nexus_repository" "apt-proxy-bionic" {
  name   = "apt-proxy-bionic"
  format = "apt"
  type   = "proxy"
  apt {
    distribution = "bionic"
  }
  storage {
    blob_store_name                = "apt-internal"
    strict_content_type_validation = true
    write_policy                   = "ALLOW_ONCE"
  }
  depends_on = [nexus_blobstore.apt-internal]
}
Once I run apply:
nexus_repository.apt-proxy-bionic: Creating...
Error: could not create repository 'apt-proxy-bionic': HTTP: 400, [ {
  "id" : "PARAMETER httpClient",
  "message" : "must not be null"
}, {
  "id" : "PARAMETER negativeCache",
  "message" : "must not be null"
}, {
  "id" : "PARAMETER proxy",
  "message" : "must not be null"
}, {
  "id" : "PARAMETER flat",
  "message" : "must not be null"
} ]
  on repositories.tf line 1, in resource "nexus_repository" "apt-proxy-bionic":
   1: resource "nexus_repository" "apt-proxy-bionic" {
```

I do have those section in my real repo and would like them to be declared even with null or empry values. But I can’t figure out how to define them. And can’t even find them in repository’s resource GO code as of here:
https://github.com/datadrivers/terraform-provider-nexus/blob/master/nexus/resource_repository.go
It would be nice to have full list of possible parameters or just 1 big example with all possible options provided. It would make it much more easier using this provider. I think it can be applied to all the resources.

**Comment by Nosmoht** [comment]
Hi @5obol,

please see the examples for `nuget_proxy` and `docker_hub` within README.md. The errors you got are only for repositories of type proxy.

**Comment by 5obol** [comment]
Hi,
Thank you for such a quick reply and action on this.
Have just went through those two examples as well. And here what I have in a TF code:

```
resource "nexus_repository" "apt-proxy-bionic" {
  name   = "apt-proxy-bionic"
  format = "apt"
  type   = "proxy"
  online = true
  apt {
    distribution = "bionic"
  }
  negative_cache {
    enabled = true
    ttl     = 1440
  }
  http_client {
      auto_block = true
  }
  proxy {
    remote_url  = "http://archive.ubuntu.com/ubuntu/"
    metadata_max_age = "1440"
    content_max_age = "1440"
  }
  storage {
    blob_store_name                = "apt-internal"
    strict_content_type_validation = true
    write_policy                   = "ALLOW_ONCE"
  }
  depends_on = [nexus_blobstore.apt-internal]
}
Apply:
$ terraform apply -input=false "planfile"
nexus_repository.apt-proxy-bionic: Creating...
Error: could not create repository 'apt-proxy-bionic': HTTP: 400, [ {
  "id" : "PARAMETER flat",
  "message" : "must not be null"
}, {
  "id" : "PARAMETER type",
  "message" : "may not be empty"
} ]
  on repositories.tf line 1, in resource "nexus_repository" "apt-proxy-bionic":
   1: resource "nexus_repository" "apt-proxy-bionic" {
ERROR: Job failed: exit code 1

**Comment by Nosmoht** [comment]
Hi @5obol ,

the issue with parameter `type` can be fixed by adding `authentication` even if you don't use username and passwort, it would at least fix the issue. We have another issue to check if authentication can be omitted.
```hcl
http_client {
      auto_block = true
      authentication {
		type = "username"
      }
  }
```

Parameter `flat` is really new to me. Which version of Nexus are u using

**Comment by Nosmoht** [comment]
Found the `flat` parameter. Seems like following is missing.
```hcl
   apt {
      distribution = "bionic"
      flat = false
   }
```

**Comment by Nosmoht** [comment]
Foo, this parameter is not yet implemented. I'll add it soon.

**Comment by 5obol** [comment]
> version

We are using Nexus 3.22.1-02

**Comment by fog1985** [comment]
> Foo, this parameter is not yet implemented. I'll add it soon.

Cool, 
Thank you @Nosmoht beforehand.
As I am facing pretty the same issue. Looking forward to having it added.

**Comment by ruedigerblock** [comment]
Moin guys,
we created a new release v1.6.2 which should address this issue.
Please check ;-)

**Comment by fog1985** [comment]
Cool! Thank you! ;)

**Comment by fog1985** [comment]
Hi @Nosmoht, 

All works well. Thank you.

1 more question. Is there a chance to get what data fields/outputs `data` source for `repository` has?
I am curious if it's possible to get for example a list of created `privileges` during the `repository` creation process and as the result create a `role` resources with those `privileges`.
If it's not a correct place to ask this question please let me know and I can raise another topic. :)

Regards,
Taras.

**Comment by fog1985** [comment]
Hi @ruedigerblock ,
Thank you as well! And including you into the thread too. :)
Went through everything and can't figure out how to get a list of created `privileges` by repository resource. Or as the result of repository creation. 
Any hints, please?
Cuz trying to create a role with those privileges included and there is no way to get them. :)

**Comment by Nosmoht** [comment]
Hi @fog1985 ,

i'm closing this ticket as you've already opened https://github.com/datadrivers/terraform-provider-nexus/issues/54 for the privileges. Thanks for your support.

**Comment by fog1985** [comment]
Sure. Thank you @Nosmoht .
