### ISSUE TITLE
 Feature request: Repository format type = raw is not available

### ISSUE THREAD

**Issue by 5obol** [datadrivers/terraform-provider-nexus#50]
Hi guys

I have found almost all the needed resources in your provider. And that is very cool.
Though 1 resource type seems to be missing or just not implemented yet.
Would be wonderful to have it added/implemented as well and be able to fully manage Nexus as code.
This is repository format = raw . I can’t find it implemented in your provider.
We use it for repository types as follow: hosted, group, proxy .

I had a look into the code here:
https://github.com/datadrivers/terraform-provider-nexus/blob/master/nexus/resource_repository.go

And don’t see that raw format is supported.
Here is the official link to the description: https://help.sonatype.com/repomanager3/formats/raw-repositories

**Comment by Nosmoht** [comment]
Hi @5obol ,

we are happy to implement this, unfortunately Nexus 3.23.0 does support RAW format via API. Lets see what the next release brings.

**Comment by fog1985** [comment]
Hi @Nosmoht ,
I have just happened to find that it seems like Nexus 3.24.0 which has not released yet but will support it:
https://github.com/sonatype/nexus-public/tree/master/plugins/nexus-repository-raw
They added it just yesterday :)
Please have a look at.

**Comment by fog1985** [comment]
Yeap. It's here:
https://github.com/sonatype/nexus-public/tree/master/plugins/nexus-repository-raw/src/main/java/org/sonatype/nexus/repository/raw/rest

**Comment by Nosmoht** [comment]
Hi @fog1985 ,

we will start with implementation as soon as 3.24.0 is out. Our feel free to send a PR ;)

**Comment by fog1985** [comment]
> Hi @fog1985 ,
> 
> we will start with implementation as soon as 3.24.0 is out. Our feel free to send a PR ;)

If I could I would have sent it already. :P) Unfortunately not so good at Go programming. I have just started studying Python recently. :)

**Comment by Nosmoht** [comment]
Implementation already done https://github.com/datadrivers/terraform-provider-nexus/pull/59.
Just waiting for a review and then we can create v1.8.0.

**Comment by Nosmoht** [comment]
We've release [v1.8.0](https://github.com/datadrivers/terraform-provider-nexus/releases/tag/v1.8.0) which supports `raw` repository format.

**Comment by fog1985** [comment]
Tested out. Works as expected.
