### ISSUE TITLE
Feaure request (https proxy): Repository --> proxy --> "Use the Nexus truststore" is not implemented.

### ISSUE THREAD

**Issue by fog1985** [datadrivers/terraform-provider-nexus#57]
Hi guys,
Using Nexus 3.23.0 can't find this option to be either enabled or disabled for the locations which use https protocol:

![image](https://user-images.githubusercontent.com/3924436/84153739-f0206200-aa6e-11ea-84df-601ff439d4bf.png)

Don't see it in a "proxy" code configuration section for the repository as well.
It would be nice to have it added. 
Thank you a lot in advance! :)

Kindest regards,
Taras.

**Comment by Nosmoht** [comment]
Hi @fog1985 ,

i couldn't find anything within Nexus API. Maybe you should ask Sonatype if this is supported via API.

**Comment by skipperza** [comment]
I contacted Sonatype to ask them. Will update the answer here.

**Comment by skipperza** [comment]
Response from Sonatype:

> You can see info about the API at http://<hosturl>:8081/#admin/system/api, then scroll down to Security: certificates
> You will notice some of the endpoints including these ones, still have a beta tag. We are planning on removing that soon, but in the meanwhile they are all usable. Hope this is what you are looking for

**Comment by Nosmoht** [comment]
Hi all,

i guess the answer from Sonatype is not what we expected. If needed, we could add resources for SSL certificate management, but still missing is how to set that check box using Nexus API.

Do we need to implement resources for SSL certificates like `nexus_ssl_truststore` and maybe a data object `nexus_ssl_truststore`?

**Comment by anmoel** [comment]
HI,

i send a new request for this feature at sonatype
https://community.sonatype.com/t/activate-use-the-nexus-truststore-for-proxy-repository-via-api/5749

**Comment by anmoel** [comment]
https://issues.sonatype.org/browse/NEXUS-26196

**Comment by qube222pl** [comment]
Feature implemented in Nexus version 3.30

**Comment by anmoel** [comment]
Hi @qube222pl,

thanks for this information.
I will remove the label "blocked" and change the prio.
I hope, we can implement this in the next few weeks.

regards
André
