### ISSUE TITLE
No field `password` available for http_client authentication section.

### ISSUE THREAD

**Issue by fog1985** [datadrivers/terraform-provider-nexus#58]
When I try to create it I get the error as follow:
```
 Error: could not update repository 'maven-release': HTTP: 400, [ {
  "id" : "FIELD password",
  "message" : "may not be empty"
} ]
```

TF code block for this looks as follow:

```
  http_client {
      blocked = false
      auto_block = false
      authentication {
        type = "username"
        username = "nexus"
        ntlm_host = ""
        ntlm_domain = ""
      }
  }
```

If I try to provide a field called `password` I got a message:
`
An argument named "password" is not expected here.
`

**Comment by fog1985** [comment]
Nexus version 3.24.0
Nexus provider version:  v1.7.0

**Comment by Nosmoht** [comment]
Hi @fog1985 ,

could you please provide complete TF resource code so we can reproduce? Seems like you're trying to ensure a maven proxy repo.

**Comment by fog1985** [comment]
Hi @Nosmoht ,

Yeap. It's Maven Proxy:

```
resource "nexus_repository" "maven-release" {
  name   = "maven-release"
  format = "maven2"
  type   = "proxy"

  maven {
    version_policy = "SNAPSHOT"
    layout_policy = "STRICT"
  }

  http_client {
      blocked = false
      auto_block = false
      # authentication {
      #   type = "username"
      #   username = "nexus"
      #   ntlm_host = ""
      #   ntlm_domain = ""
      # }
  }

  negative_cache {
    enabled = false
    ttl     = 0
  }

  proxy {
    remote_url  = "https://remote_url/"
    metadata_max_age = "1440"
    content_max_age = "-1"
  }

  storage {
    blob_store_name                = "maven"
    strict_content_type_validation = true
    write_policy                     = "ALLOW"
  }
}
```

**Comment by Nosmoht** [comment]
Thanks @fog1985, we are now able to reproduce the error.

**Comment by Nosmoht** [comment]
Hi all,

the attribute is undocumented within Nexus 3.24.0 API but available for use. I'm currently working on the implementation.

**Comment by android-leha** [comment]
I created PR #64 to fix this issue.

But I have another problem:
@Nosmoht, may be you aware:
I need also mark this checkbox
![image](https://user-images.githubusercontent.com/1458524/85224864-eb946b80-b3d5-11ea-87ca-fdcd8e2787a0.png)

Is this parameter existed in API?

After I rerun plan, this mark become disable

**Comment by sboardwell** [comment]
Hi All, any news on this or #64? Is there anything blocking the merge?

**Comment by Nosmoht** [comment]
I‘ll create a new release with your change this weekend. Stay tuned 😉

**Comment by Nosmoht** [comment]
There is one thing left to do. As the Nexus API does not return the password, we must set it into state from input value.

**Comment by android-leha** [comment]
@Nosmoht do you have any example, how it can be done?

**Comment by Nosmoht** [comment]
@android-leha what exactly do you mean ?
