### ISSUE TITLE
Proposal: add possibility to get a list of repositories in data source. 

### ISSUE THREAD

**Issue by fog1985** [datadrivers/terraform-provider-nexus#69]
Hi guys,
I have tried to get a list of repositories with the usage of data source for Repositories:
```
data "nexus_repository" "all_repos" {
  name = ""
  format = "docker"
}
```
But it requires explicit `name`. `No asterisk or RegExp is accepted`. E.G. it can get only 1 repo. Base on format etc. 
Would be nice to have it done in the way that allows just to get a full list of Repositories based on type or format etc. 
So that we could just parse for any reason all the repositories inside of Nexus.

**Comment by Nosmoht** [comment]
Sounds like a good idea that we should implement.
