### ISSUE TITLE
Terraform 0.13 support

### ISSUE THREAD

**Issue by kuzmacska** [datadrivers/terraform-provider-nexus#80]
Could you guys add support for Terraform 0.13?
Now it is mandatory to upload binary like in the guide below:
https://www.terraform.io/upgrade-guides/0-13.html#in-house-providers

**Comment by Skaronator** [comment]
Duplicate of #76 which has been closed even though it isn't done.

**Comment by anmoel** [comment]
Hi,

now we have added our provider to the terraform registry.
see https://registry.terraform.io/providers/datadrivers/nexus/latest

kind regards

André
