### ISSUE TITLE
Proposal: Rename data_source_user{_test}.go -> data_source_security_user{_test}.go

### ISSUE THREAD

**Issue by ruedigerblock** [datadrivers/terraform-provider-nexus#84]
Within the Nexus API security management has been placed after the /security/ subpath.
This has also been considered in the naming of security_ldap and security_realms. Since users is part of the security management it would make sense to rename those files to.

**Comment by anmoel** [comment]
maybe, we should duplicate the resource and add a deprecation warning on the old resource
