### ISSUE TITLE
Publish provider to https://registry.terraform.io/

### ISSUE THREAD

**Issue by cpesch** [datadrivers/terraform-provider-nexus#85]
Hi,

it really reduces the barrier to use this provider if it was registred at https://registry.terraform.io/
Please consider registering it.

Best regards
Christian

PS: Yes, I know #76 and #80 exist

**Comment by anmoel** [comment]
Hi,

now we have added our provider to the terraform registry.
see https://registry.terraform.io/providers/datadrivers/nexus/latest

kind regards

André

**Comment by cpesch** [comment]
Thank you :-)
