### ISSUE TITLE
Add documentation about encryption in nexus_blobstore

### ISSUE THREAD

**Issue by chewrocca** [datadrivers/terraform-provider-nexus#94]
Looks like there is documentation missing about the encryption stanza in nexus_blobstore.  

This encryption stanza seems to work but it appears to be missing from the documentation.  

```sh
    encryption {
      encryption_type = "s3ManagedEncryption"
    }
```

**Comment by anmoel** [comment]
Hi @chewrocca,

thanks for the report.

i will look on it.

regards
André
