### ISSUE TITLE
Add support for writableMember in group

### ISSUE THREAD

**Issue by chewrocca** [datadrivers/terraform-provider-nexus#95]
Please add support for writableMember in group.  

Related to this [Add writableMember struct to RepositoryGroup #46](https://github.com/datadrivers/go-nexus-client/issues/46)

**Comment by anmoel** [comment]
Hi @chewrocca,

thanks for your report.
We will add this requested feature to our list and will implement them in the next few weeks.

regards
André

**Comment by anmoel** [comment]
Hi @chewrocca, 

please use the new resource `nexus_repository_docker_group ` of our latest provider version. This pro feature is implemented in the new resource.
